# syntax=docker/dockerfile:1

FROM alpine:3.21

ARG TARGETPLATFORM
ARG VERSION=dev
ARG COMMIT=none

LABEL org.opencontainers.image.title="filebrowser" \
      org.opencontainers.image.description="Web file browser" \
      org.opencontainers.image.url="https://github.com/skidoodle/filebrowser" \
      org.opencontainers.image.source="https://github.com/skidoodle/filebrowser" \
      org.opencontainers.image.licenses="BSD-3-Clause" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.revision="${COMMIT}"

RUN apk add --no-cache ca-certificates mailcap tzdata su-exec && \
    mkdir -p /data /cache /app /db && \
    chown -R 1000:1000 /data /cache /app /db

COPY $TARGETPLATFORM/filebrowser /usr/local/bin/filebrowser
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

ENV FILEBROWSER_ROOT=/data \
    FILEBROWSER_CACHEDIR=/cache \
    FILEBROWSER_DATABASE=/db/filebrowser.db

VOLUME ["/data", "/cache", "/db"]

WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["docker-entrypoint.sh"]
