# syntax=docker/dockerfile:1

FROM alpine:3.21 AS runtime
RUN apk add --no-cache ca-certificates mailcap tzdata && \
    mkdir -p /data /cache && \
    chown -R 1000:1000 /data /cache

FROM scratch

ARG TARGETPLATFORM
ARG VERSION=dev
ARG COMMIT=none

LABEL org.opencontainers.image.title="filebrowser" \
      org.opencontainers.image.description="Stateless, guest-only web file browser" \
      org.opencontainers.image.url="https://github.com/skidoodle/filebrowser" \
      org.opencontainers.image.source="https://github.com/skidoodle/filebrowser" \
      org.opencontainers.image.licenses="MIT" \
      org.opencontainers.image.version="${VERSION}" \
      org.opencontainers.image.revision="${COMMIT}"

COPY $TARGETPLATFORM/filebrowser /usr/local/bin/filebrowser
COPY --from=runtime /etc/ssl/certs/ca-certificates.crt /etc/ssl/certs/ca-certificates.crt
COPY --from=runtime /etc/mime.types /etc/mime.types
COPY --from=runtime /usr/share/zoneinfo /usr/share/zoneinfo
COPY --from=runtime --chown=1000:1000 /data /data
COPY --from=runtime --chown=1000:1000 /cache /cache

VOLUME ["/data", "/cache"]

USER 1000:1000
WORKDIR /app

EXPOSE 8080

ENTRYPOINT ["filebrowser"]
